version: '3.8'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 80:80
      - 443:443
      - 81:81
    restart: unless-stopped

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${docker_path}/nginx-proxy-manager:/config

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    hostname: sonarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Asia/Riyadh"
      UMASK_SET: 022
    depends_on:
      - jackett
      - qbittorrent
    ports:
      - 8989:8989
    volumes:
      - ${docker_path}/sonarr:/config
      - ${media_path}/TV_Shows:/tv
      - ${docker_path}/downloads:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    hostname: radarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Asia/Riyadh"
      UMASK_SET: 022
    depends_on:
      - jackett
      - qbittorrent
    ports:
      - 7878:7878
    volumes:
      - ${docker_path}/radarr:/config
      - ${media_path}/Movies:/movies
      - ${docker_path}/downloads:/downloads

  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: unless-stopped
    hostname: plex
    environment:
      TZ: "Asia/Riyadh"
      PLEX_CLAIM: "claim-CDsk8KCce1gvEz-afh3M"
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${docker_path}/plex:/config
      - ${media_path}:/data
      - ${others_path}:/devops
    
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Asia/Riyadh"
      #- JELLYFIN_PublishedServerUrl=jellyfin #optional
    volumes:
      - ${docker_path}/jellyfin:/config
      - ${media_path}:/media
      - ${others_path}:/devops
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    hostname: jackett
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Asia/Riyadh"
    ports:
      - 9117:9117
    volumes:
      - ${docker_path}/jackett:/config

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    restart: unless-stopped
    hostname: prowlarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Asia/Riyadh"
    ports:
      - 9696:9696
    volumes:
      - ${docker_path}/prowlarr:/config

  overseerr:
    container_name: overseerr
    image: linuxserver/overseerr:latest
    restart: unless-stopped
    hostname: overseerr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Asia/Riyadh"
      BASE_URL: "http://localhost:5055"
    depends_on:
      - sonarr
      - radarr
      - plex
    ports:
      - 5055:5055
    volumes:
      - ${media_path}:/data
      - ${docker_path}/overseerr:/config

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    hostname: qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Asia/Riyadh"
    ports:
      - 8080:8080
    volumes:
      - ${docker_path}/qbittorrent:/config
      - ${docker_path}/downloads:/downloads
      - ${media_path}:/watch

networks:
  home-media:
      name: home-media
